/**
 *******************************************************************************
 * @file    eq_params.h
 * @brief   EQ parameters (type,f0,Q,sqrtA) for the follow EQ styles.
 *
 * @author  Auto Generated by Parametric Equalizer Plot Software
 * @version V1.0.0
 *
 * $Created: Apr 18 2014 18:06:49$:
 *
 * &copy; Shanghai Mountain View Silicon Technology Co.,Ltd. All rights reserved.
 *******************************************************************************
 */

#ifndef __EQ_PARAMS_H__
#define __EQ_PARAMS_H__

#ifdef  __cplusplus
extern "C" {
#endif//__cplusplus

#include "type.h"

#define EQ_STYLE_CNT   10 /* Count of total EQ style */
#define EQ_STYLE_SUM   EQ_STYLE_CNT

/**
 * @brief  Select the "Id"-th EQ style
 * @param  SamplingRate sample rate
 * @param  Id the selected EQ style ID, its defination as follow:
 *    @arg 0: CLASSICAL
 *    @arg 1: VOCAL BOOSTER
 *    @arg 2: FLAT
 *    @arg 3: BASS BOOSTER
 *    @arg 4: BASS REDUCER
 *    @arg 5: TREBLE BOOSTER
 *    @arg 6: TREBLE REDUCER
 *    @arg 7: POP
 *    @arg 8: ROCK
 *    @arg 9: JAZZ
 * @return NONE
 */
void EqStyleSelect(uint16_t SamplingRate, uint32_t Id);

#ifdef  __cplusplus
}
#endif//__cplusplus

#endif//__EQ_PARAMS_H__
