/**
 *******************************************************************************
 * @file    eq_params.c
 * @brief   EQ parameters (type,f0,Q,sqrtA) for the follow EQ styles.
 *
 * @author  Auto Generated by Parametric Equalizer Plot Software
 * @version V1.0.0
 *
 * $Created: Apr 18 2014 18:06:49$:
 *
 * &copy; Shanghai Mountain View Silicon Technology Co.,Ltd. All rights reserved.
 *******************************************************************************
 */

#include "eq.h"
#include "eq_params.h"

typedef struct _EqSet
{
	const EqFilterParams* Params[EQ_STYLE_CNT];  /**< EQ filter parameters */
	const uint8_t         Count[EQ_STYLE_CNT];   /**< EQ filter count      */
	const uint32_t        Pregain[EQ_STYLE_CNT]; /**< data format Q4.16    */
}EqSet;

//EQ style: Classical
static const EqFilterParams _EqStyle0[4] = 
{
	{ 0x0001, 0x010a, 0x00b7, 0x04a3 }, // Parameters for filter 0
	{ 0x0000, 0x027f, 0x0341, 0x0384 }, // Parameters for filter 1
	{ 0x0000, 0x06ee, 0x02d4, 0x03cb }, // Parameters for filter 2
	{ 0x0002, 0x0eb2, 0x0124, 0x048f }, // Parameters for filter 4
};

//EQ style: Vocal Booster
static const EqFilterParams _EqStyle1[4] = 
{
	{ 0x0000, 0x0060, 0x01f9, 0x0377 }, // Parameters for filter 1
	{ 0x0000, 0x021f, 0x014c, 0x0480 }, // Parameters for filter 2
	{ 0x0000, 0x09a3, 0x0306, 0x0420 }, // Parameters for filter 3
	{ 0x0002, 0x29e3, 0x02cc, 0x03ce }, // Parameters for filter 4
};

/*
//EQ style: Flat
static const EqFilterParams _EqStyle2[0] = 
{
};
*/

//EQ style: Bass Booster
static const EqFilterParams _EqStyle3[1] = 
{
	{ 0x0001, 0x0082, 0x0220, 0x04b3 }, // Parameters for filter 0
};

//EQ style: Bass Reducer
static const EqFilterParams _EqStyle4[1] = 
{
	{ 0x0001, 0x00e8, 0x026c, 0x0360 }, // Parameters for filter 0
};

//EQ style: Treble Booster
static const EqFilterParams _EqStyle5[1] = 
{
	{ 0x0002, 0x089b, 0x0207, 0x04bb }, // Parameters for filter 4
};

//EQ style: Treble Reducer
static const EqFilterParams _EqStyle6[1] = 
{
	{ 0x0002, 0x0776, 0x02d3, 0x0368 }, // Parameters for filter 4
};

//EQ style: Pop
static const EqFilterParams _EqStyle7[3] = 
{
	{ 0x0001, 0x00cc, 0x0225, 0x03c2 }, // Parameters for filter 0
	{ 0x0000, 0x02ca, 0x01e8, 0x047c }, // Parameters for filter 1
	{ 0x0002, 0x1233, 0x028c, 0x03c8 }, // Parameters for filter 4
};

//EQ style: Rock
static const EqFilterParams _EqStyle8[3] = 
{
	{ 0x0001, 0x00c4, 0x0284, 0x0498 }, // Parameters for filter 0
	{ 0x0000, 0x03c3, 0x0133, 0x03bf }, // Parameters for filter 1
	{ 0x0002, 0x0d8f, 0x0214, 0x0485 }, // Parameters for filter 4
};

//EQ style: Jazz
static const EqFilterParams _EqStyle9[3] = 
{
	{ 0x0001, 0x0070, 0x0185, 0x0482 }, // Parameters for filter 0
	{ 0x0000, 0x0293, 0x036a, 0x03c3 }, // Parameters for filter 2
	{ 0x0002, 0x11d8, 0x0224, 0x0454 }, // Parameters for filter 4
};

const EqSet EQ_SET = 
{
	{
		_EqStyle0,	//Classical
		_EqStyle1,	//Vocal Booster
		NULL,		//Flat
		_EqStyle3,	//Bass Booster
		_EqStyle4,	//Bass Reducer
		_EqStyle5,	//Treble Booster
		_EqStyle6,	//Treble Reducer
		_EqStyle7,	//Pop
		_EqStyle8,	//Rock
		_EqStyle9,	//Jazz
	},
	{
		4,
		4,
		0,
		1,
		1,
		1,
		1,
		3,
		3,
		3,
	},
	{
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
	}
};

void EqStyleSelect(uint16_t SamplingRate, uint32_t Id)
{
    EqStyleConfigure(SamplingRate, (EqFilterParams*)EQ_SET.Params[Id], EQ_SET.Count[Id], EQ_SET.Pregain[Id]);
}
